// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qorkfgvhzpllhpumznjd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFvcmtmZ3ZoenBsbGhwdW16bmpkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwODc1ODcsImV4cCI6MjA3MDY2MzU4N30.IWfWzePH8qAT-hOcN0iorMx9eH0H9a8rEZQmSTERIuc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});