// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://difqtvjwuuvlbzrxsnlj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRpZnF0dmp3dXV2bGJ6cnhzbmxqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5MzIwMDYsImV4cCI6MjA3MDUwODAwNn0.2ZWj0Wb0qJ8sw350UeOKqWeZVdkkmlAfCo6kVLCgveo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});